repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
   - id: nbqa-black
     additional_dependencies: [black==22.3.0]
   - id: nbqa-isort
     additional_dependencies: [isort==5.6.4]

- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
